export const copy = {
  en: {
    scrollCue:'Scroll to explore', skipStory:'Skip story', storyFinish:'Ready to decide?', storyFinishDetail:'Rate the allocation first. The mathematical results appear afterward.',
    skipToContent:'Skip to content', heroEyebrow:'A little experiment in fairness', heroTitle:'Judge first. Learn why afterward.', heroIntro:'Three objects. Two people. Would you call this fair? Make your judgment before the mathematics enters the room.', tryExample:'Try the example', howItWorks:'How it works', stepOne:'See who gets what', stepOneDetail:'Meet the people and inspect each item before taking a position.', stepTwo:'Trust your intuition', stepTwoDetail:'Give the allocation a fairness rating from one to five.', stepThree:'See the reasoning', stepThreeDetail:'Compare your answer with EF1, EFX and Nash social welfare.', createYourOwn:'Create your own case', heroAside:'A question worth asking', heroQuestion:'Can an allocation feel fair and still fail a mathematical test?', siteTagline:'A hands-on guide to dividing things fairly',
    valuations:'Valuations', people:'People', goods:'Items', preview:'Preview before publishing', immutableHint:'Published values cannot be edited. Check them before continuing.', valueHint:'Use whole numbers from 0 to 1,000,000.', assignmentProgress:'Items assigned', shareLink:'Copy case link', copied:'Link copied', copyFallback:'Copy this URL to share', noEntries:'Only the baseline exists so far. Assign the items to add yours.', selectOwner:'Choose a person', submitting:'Submitting…', invalidNames:'Use unique names between 1 and 80 characters.', invalidValues:'Enter whole numbers from 0 to 1,000,000.', notFound:'We could not find that page.', backHome:'Back to home',
    fractionalNote:'An estimate for divisible items, not the optimal indivisible allocation.',
    judgeEyebrow:'First, your judgment', judgeTitle:'Does this feel fair to you?', judgeHint:'Look at who receives each item. The mathematical results stay hidden until you rate.', chooseRating:'Choose a score from 1 to 5', ratingScale:'1 means very unfair; 5 means very fair.', resultsTitle:'The reasoning behind the result', votes:'Responses', average:'Average rating', ratingCount:'ratings', meetsCriterion:'Meets the criterion', failsCriterion:'Does not meet the criterion', witness:'Example of envy', positiveConvention:'EFX here considers items valued positively by the envious person.', surveyCaveat:'Anonymous convenience feedback, not a representative survey.', bundleValue:'Bundle value', showResults:'Your rating was recorded. Here is what the mathematics says.', previousResults:'You have already rated this allocation in this browser.',
    languageName:'English', otherLanguage:'繁體中文', homeTitle:'Fair division learning site', newCase:'New case', publishCase:'Publish case', addAgent:'Add agent', addItem:'Add item', submitAllocation:'Submit allocation', fairnessLabel:'Fairness', submitRating:'Submit rating', nswScore:'NSW score', ef1:'EF1', efx:'EFX', leaderboard:'Leaderboard', allocation:'Allocation', baseline:'Round-robin baseline', visitor:'Visitor allocation', fractional:'Fractional comparison', fractionalEstimated:'Estimated fractional NSW', fractionalPending:'Fractional estimate pending', fractionalUnavailable:'Fractional comparison unavailable', retry:'Retry', validationError:'Please check the inputs and try again.', networkError:'Network error; retry.', lesson:'Judge an allocation before seeing EF1, EFX and Nash social welfare. Computing a submitted NSW is straightforward; optimizing indivisible NSW is computationally hard. EF1 exists for nonnegative additive goods; EFX uses positively valued goods here. Ratings are anonymous convenience feedback, not representative research.', veryUnfair:'Very unfair', veryFair:'Very fair', shareCase:'Share case', shareAllocation:'Share allocation', ownerOf:'owner', alreadyRated:'This browser has already rated this allocation; results are shown without another vote.'
  },
  'zh-TW': {
    scrollCue:'向下捲動探索', skipStory:'略過故事', storyFinish:'準備好判斷了嗎？', storyFinishDetail:'先評價這項分配，提交後再查看數學結果。',
    skipToContent:'跳至主要內容', heroEyebrow:'一場關於公平的小實驗', heroTitle:'先判斷，再理解原因。', heroIntro:'三件物品，兩位參與者。你覺得這樣公平嗎？先憑直覺判斷，再看看數學怎麼說。', tryExample:'試試範例', howItWorks:'如何使用', stepOne:'看看誰拿到什麼', stepOneDetail:'認識參與者，先了解每件物品的歸屬。', stepTwo:'相信你的直覺', stepTwoDetail:'為這項分配給出一到五分的公平評價。', stepThree:'了解背後的理由', stepThreeDetail:'比較你的答案與 EF1、EFX 和納許社會福利。', createYourOwn:'建立自己的案例', heroAside:'值得思考的問題', heroQuestion:'一項分配可能感覺公平，卻不符合數學上的公平嗎？', siteTagline:'動手探索如何公平分配',
    valuations:'估值表', people:'參與者', goods:'物品', preview:'發布前預覽', immutableHint:'發布後無法修改估值，請先確認內容。', valueHint:'請輸入 0 到 1,000,000 的整數。', assignmentProgress:'已分配物品', shareLink:'複製案例連結', copied:'已複製連結', copyFallback:'複製這個網址分享', noEntries:'目前只有基準分配。分配物品來加入你的版本。', selectOwner:'選擇參與者', submitting:'提交中…', invalidNames:'名稱須為 1 到 80 個字，且不可重複。', invalidValues:'請輸入 0 到 1,000,000 的整數。', notFound:'找不到這個頁面。', backHome:'返回首頁',
    fractionalNote:'這是物品可分割時的數值估計，並非不可分割分配的最佳解。',
    judgeEyebrow:'先憑直覺判斷', judgeTitle:'你覺得這樣公平嗎？', judgeHint:'看看每件物品分給了誰。提交評分前不會顯示數學結果。', chooseRating:'請選擇 1 到 5 分', ratingScale:'1 分表示非常不公平，5 分表示非常公平。', resultsTitle:'數學結果怎麼說', votes:'回覆數', average:'平均評分', ratingCount:'次評分', meetsCriterion:'符合條件', failsCriterion:'不符合條件', witness:'羨慕的例子', positiveConvention:'本站的 EFX 只考慮羨慕者正估值的物品。', surveyCaveat:'匿名便利樣本回饋，不是具代表性的調查。', bundleValue:'獲得物品的估值', showResults:'已記錄你的評分，看看數學結果。', previousResults:'此瀏覽器已評價過這項分配。',
    languageName:'繁體中文', otherLanguage:'English', homeTitle:'公平分配教學網站', newCase:'建立案例', publishCase:'發布案例', addAgent:'新增參與者', addItem:'新增物品', submitAllocation:'提交分配', fairnessLabel:'公平程度', submitRating:'提交評分', nswScore:'NSW 分數', ef1:'EF1', efx:'EFX', leaderboard:'排行榜', allocation:'分配', baseline:'輪流挑選基準', visitor:'訪客分配', fractional:'可分割版本比較', fractionalEstimated:'可分割版本 NSW 數值估計', fractionalPending:'可分割版本計算中', fractionalUnavailable:'可分割版本比較暫不可用', retry:'重試', validationError:'請檢查輸入後再試一次。', networkError:'網路錯誤，請重試。', lesson:'請先評價一項分配，再查看 EF1、EFX 與納許社會福利。計算已提交分配的 NSW 很直接；最佳化不可分割 NSW 在計算上困難。非負可加估值下 EF1 存在；本站 EFX 採用正估值物品定義。匿名評分只是便利樣本回饋，不是具代表性的研究。', veryUnfair:'非常不公平', veryFair:'非常公平', shareCase:'分享案例', shareAllocation:'分享分配', ownerOf:'歸屬', alreadyRated:'此瀏覽器已評價過這項分配；不再投票並直接顯示結果。'
  }
} as const;
export type Locale = keyof typeof copy;
export const locales: Locale[] = ['zh-TW','en'];
