import type { NarrativeScenario } from './types';

const t = (zh: string, en: string) => ({ 'zh-TW': zh, en });

export const NARRATIVE_SCENARIOS: NarrativeScenario[] = [
  {
    id: 'guild',
    act: 1,
    era: t('大宋紹聖二年 · 汴京', 'Shaosheng 2, Northern Song · Bianjing'),
    title: t('彩帛行師徒析產案', 'The Bianjing Guild Partition'),
    concept: 'EF1',
    poster: '/game/posters/guild.webp',
    opening: t(
      '彩帛行的燈火整夜未熄。兩名師兄弟守著恩師留下的四件遺物，誰也不肯先退一步。陸老會首把金算盤推到你面前：「提刑大人，今夜若定不了分，明日整條街都要看我們的笑話。」',
      'The guild lanterns have burned through the night. Two apprentices guard four heirlooms, neither willing to yield. Elder Lu pushes a golden abacus toward you. “Magistrate, settle this before the whole street wakes.”',
    ),
    storyBeats: [
      {
        speaker: t('旁白', 'Narrator'),
        text: t('彩帛行的燈火整夜未熄。恩師留下的四件遺物橫在長案上，兩名師兄弟各守一端，誰也不肯先退。', 'The guild lanterns have burned through the night. Four heirlooms lie across the long table while two apprentices guard opposite ends, neither willing to yield.'),
        action: t('鏡面搖著燈影，金算盤的珠聲在沉默裡格外清楚。', 'Lanterns tremble in the mirror; abacus beads cut through the silence.'),
        focusTargetId: 'mirror',
        tone: 'narrator',
      },
      {
        speaker: t('陸老會首', 'Elder Lu'),
        text: t('提刑大人，您總算來了。今夜若定不了分，明日整條汴京彩帛行都要看我們的笑話。', 'Magistrate, at last. If no division is settled tonight, every textile guild in Bianjing will mock us by morning.'),
        action: t('老會首把金算盤推到你面前，疲憊地退到長案旁。', 'The elder pushes a golden abacus toward you and steps wearily aside.'),
        tone: 'character',
      },
      {
        speaker: t('沈景和', 'Shen Jinghe'),
        text: t('二十年官差應酬、番商往來，哪一樁不是我談下來的？老店的商譽，不能交給只懂染布的人。', 'For twenty years I won over officials and foreign merchants. The shop’s reputation cannot be handed to a man who only knows dye.'),
        action: t('沈景和護在琉璃鏡前，拇指仍一刻不停地撥著算珠。', 'Shen Jinghe guards the mirror, his thumb never leaving the abacus.'),
        focusTargetId: 'jinghe',
        tone: 'character',
      },
      {
        speaker: t('顧雲錦', 'Gu Yunjin'),
        text: t('若不是我守著染爐試色，他拿什麼布去招待豪客？染譜與師門名分，我一步也不讓。', 'Without me tending the dye vats, what cloth would he show those patrons? I will not surrender the manual or our lineage.'),
        action: t('顧雲錦染青的十指壓住卷軸，抬眼直視師兄。', 'Gu Yunjin presses dye-stained fingers to the scroll and meets his senior’s stare.'),
        focusTargetId: 'yunjin',
        tone: 'character',
      },
      {
        speaker: t('系統 · 查案指引', 'System · Investigation'),
        text: t('先詢問兩位當事人，聽懂同一件物品在不同人眼中的價值。取得必要口供後，系統會告訴你如何開始分配。', 'Question both claimants first. Learn why the same object carries a different value to each person. Once the required testimony is recorded, the allocation task will open.'),
        action: t('可點擊場景人物，或使用下方的詢問按鈕。', 'Select a character in the scene or use the interview buttons below.'),
        tone: 'system',
      },
    ],
    allocationPrompt: t('把四件遺物放上兩方案台。人物會回應你的每一次移動。', 'Place all four heirlooms on the two trays. The disputants will react to every move.'),
    agents: [
      { id: 'jinghe', name: t('沈景和', 'Shen Jinghe'), role: t('師兄 · 商人', 'Senior apprentice · Merchant'), color: '#2f7d71' },
      { id: 'yunjin', name: t('顧雲錦', 'Gu Yunjin'), role: t('師弟 · 染匠', 'Junior apprentice · Dyer'), color: '#b95d3b' },
    ],
    items: [
      { id: 'mirror', name: t('泰西琉璃鏡', 'Western glass mirror'), shortName: t('琉璃鏡', 'Mirror'), description: t('能映出毫髮的稀世舶來鏡。', 'A rare imported mirror that catches every detail.') },
      { id: 'dye-scroll', name: t('天蠶秘色染譜', 'Celestial silk dye manual'), shortName: t('染譜', 'Dye manual'), description: t('記載天青與秘色配方的孤本。', 'The only surviving record of two secret dyes.') },
      { id: 'plaque', name: t('老字號金字牌匾', 'Gilded guild plaque'), shortName: t('牌匾', 'Plaque'), description: t('商譽與師門正統都繫在這塊匾上。', 'Both commercial trust and lineage rest on this plaque.') },
      { id: 'vase', name: t('長安官窯梅花瓶', 'Chang’an plum vase'), shortName: t('梅花瓶', 'Vase'), description: t('可供清賞，也可在缺銀時典當。', 'An elegant antique that can also become ready silver.') },
    ],
    values: [[50, 5, 30, 15], [15, 45, 35, 5]],
    clues: [
      { id: 'guild-jinghe', targetId: 'jinghe', kind: 'agent', speaker: t('沈景和', 'Shen Jinghe'), unlocksAgentId: 'jinghe', text: t('經商最要緊的是一個「信」字。琉璃鏡能招來權貴，在我心裡值 50 分；老牌匾就是老客認店的根本，值 30 分。師弟有手藝，離了老店也不至於沒飯吃。', 'Trade lives on trust. The mirror draws powerful clients and is worth 50 to me. The old plaque carries our reputation and is worth 30. My junior still has his craft.') },
      { id: 'guild-yunjin', targetId: 'yunjin', kind: 'agent', speaker: t('顧雲錦', 'Gu Yunjin'), unlocksAgentId: 'yunjin', text: t('染譜是恩師一生心血，值 45 分；牌匾代表師門名分，至少值 35 分。若都落到只懂應酬的人手裡，我死後拿什麼臉見恩師？', 'The dye manual is our master’s life work, worth 45. The plaque proves our lineage, worth 35. If both go to a man of banquets, how could I face our master?') },
      { id: 'guild-mirror', targetId: 'mirror', kind: 'item', speaker: t('旁白', 'Narrator'), text: t('孔雀石鏡框映著燈火。商人看見豪客，匠人只看見一件浮華擺設。', 'Lantern light runs across the malachite frame. A merchant sees patrons; a craftsman sees ornament.') },
      { id: 'guild-scroll', targetId: 'dye-scroll', kind: 'item', speaker: t('旁白', 'Narrator'), text: t('卷上密密記著靛藍、朱砂的比例與火候。外行看字，內行看見的是一生。', 'Indigo, cinnabar, temperature, timing—the outsider sees notes; the artisan sees a lifetime.') },
      { id: 'guild-plaque', targetId: 'plaque', kind: 'item', speaker: t('陸老會首', 'Elder Lu'), text: t('這塊匾只有一塊，卻同時是商譽與名分。真正難分的，往往不是最昂貴的東西。', 'There is one plaque, but it carries both reputation and legitimacy. The hardest thing to divide is not always the costliest.') },
      { id: 'guild-vase', targetId: 'vase', kind: 'item', speaker: t('旁白', 'Narrator'), text: t('梅花瓶安靜立在桌角。它不是任何人的命根，卻可能成為調整分配的最後一枚砝碼。', 'The vase waits at the table’s edge—not anyone’s lifeline, but perhaps the final counterweight.') },
    ],
    requiredClueIds: ['guild-jinghe', 'guild-yunjin'],
    masterAllocation: [0, 1, 1, 0],
  },
  {
    id: 'yamen',
    act: 2,
    era: t('明嘉靖三十五年 · 松江府', 'Jiajing 35, Ming · Songjiang Prefecture'),
    title: t('染坊宗祧鬮分案', 'The Songjiang Inheritance Trial'),
    concept: 'EFX',
    poster: '/game/posters/yamen.webp',
    opening: t(
      '驚堂木一響，三份互相矛盾的憑據同時攤上公案：大明律、舉人功名與帶血指印的養老鬮書。堂外族人越聚越多，水力染坊的木輪仍在雨中轉動。',
      'The gavel falls. Three claims cover the bench: the Great Ming Code, an examination title, and a care contract marked in blood. Outside, the clan gathers while the mill wheel turns in rain.',
    ),
    storyBeats: [
      {
        speaker: t('旁白', 'Narrator'),
        text: t('驚堂木一響，三份互相矛盾的憑據同時攤上公案：大明律、舉人功名，以及帶血指印的養老鬮書。', 'The gavel falls. Three conflicting claims cover the bench: the Great Ming Code, an examination title, and a care contract marked in blood.'),
        action: t('堂外雨聲與染坊木輪聲交疊，族人已把衙門圍得水洩不通。', 'Rain and the mill wheel beat together while the clan crowds the yamen gates.'),
        focusTargetId: 'watermill',
        tone: 'narrator',
      },
      {
        speaker: t('趙知縣', 'Magistrate Zhao'),
        text: t('提刑大人，三方一個講宗法，一個講功名，一個攥著鬮書。判得不好，明日全城宗族就要械鬥！', 'Magistrate, one invokes lineage, one status, and one his contract. Rule poorly and the clans may be fighting by morning.'),
        action: t('趙知縣按住驚堂木，示意三人依次陳情。', 'Magistrate Zhao holds down the gavel and orders each claimant to speak in turn.'),
        tone: 'character',
      },
      {
        speaker: t('裴伯謙', 'Pei Boqian'),
        text: t('我是長房承祧。祖宅與御賜金匾若不歸我，裴家宗法置於何地？', 'I am the eldest lineage heir. If the residence and imperial plaque do not pass to me, what remains of Pei family law?'),
        action: t('裴伯謙展開《大明律》，把卷首重重壓在案上。', 'Pei Boqian opens the Great Ming Code and plants it heavily on the bench.'),
        focusTargetId: 'boqian',
        tone: 'character',
      },
      {
        speaker: t('裴仲文', 'Pei Zhongwen'),
        text: t('明年春闈在即。沒有金匾的聲望、沒有別院苦讀，我這舉人功名又有何用？', 'The metropolitan examination is next spring. Without the plaque’s standing or the retreat for study, what use is my title?'),
        action: t('裴仲文抱緊書卷，目光卻始終沒有離開金匾。', 'Pei Zhongwen grips his books, but never takes his eyes from the plaque.'),
        focusTargetId: 'zhongwen',
        tone: 'character',
      },
      {
        speaker: t('薛守成', 'Xue Shoucheng'),
        text: t('我替岳父守了二十年染坊，只求留下這條活路。兩位少爺嫌它髒，我卻靠它養活裴家上下。', 'I kept this mill alive for my father-in-law for twenty years. The young masters call it dirty; its work fed their whole household.'),
        action: t('薛守成攤開掌心，長年染作留下的裂痕清晰可見。', 'Xue Shoucheng opens his palms, showing cracks left by decades of dye work.'),
        focusTargetId: 'shoucheng',
        tone: 'character',
      },
      {
        speaker: t('系統 · 查案指引', 'System · Investigation'),
        text: t('三人的訴求不能只按市價判斷。逐一取得估值口供；當關鍵資料齊全，系統會交付五件祖產的分配任務。', 'Market price alone cannot settle these claims. Record each valuation; once the evidence is complete, the five-estate allocation task will open.'),
        action: t('點擊三位當事人，查明他們真正不能失去的是什麼。', 'Select all three claimants and discover what each truly cannot lose.'),
        tone: 'system',
      },
    ],
    allocationPrompt: t('五件祖產、三位繼承人。找出「拿走某一件」與「拿走任一件」的差別。', 'Five estates, three heirs. Discover the difference between removing one item and removing any item.'),
    agents: [
      { id: 'boqian', name: t('裴伯謙', 'Pei Boqian'), role: t('長子 · 承祧者', 'Eldest son · Lineage heir'), color: '#846b3b' },
      { id: 'zhongwen', name: t('裴仲文', 'Pei Zhongwen'), role: t('次子 · 舉人', 'Second son · Scholar'), color: '#526f82' },
      { id: 'shoucheng', name: t('薛守成', 'Xue Shoucheng'), role: t('贅婿 · 染坊掌事', 'Son-in-law · Mill steward'), color: '#477c66' },
    ],
    items: [
      { id: 'house', name: t('宗祠祖宅正院', 'Ancestral residence'), shortName: t('祖宅', 'Residence'), description: t('承祧正朔所繫的七進大宅。', 'A seven-court residence embodying clan legitimacy.') },
      { id: 'imperial-plaque', name: t('御賜「積善之家」金匾', 'Imperial virtue plaque'), shortName: t('金匾', 'Imperial plaque'), description: t('先帝御賜，也是官場聲譽的護身符。', 'An imperial gift and a shield of official reputation.') },
      { id: 'shop', name: t('城南臨街三進商鋪', 'South-city storefront'), shortName: t('商鋪', 'Storefront'), description: t('帶來穩定現金收益的布匹門面。', 'A textile storefront with reliable income.') },
      { id: 'study', name: t('別院書香退思居', 'Retreat study'), shortName: t('書齋', 'Study'), description: t('竹林深處的讀書會友之所。', 'A quiet bamboo retreat for study and guests.') },
      { id: 'watermill', name: t('水力大染坊', 'Water-powered dye mill'), shortName: t('染坊', 'Dye mill'), description: t('每日可出百匹雲錦的家業命脈。', 'The industrial heart of the estate.') },
    ],
    values: [[45, 35, 10, 5, 5], [30, 40, 10, 20, 0], [5, 0, 20, 5, 70]],
    clues: [
      { id: 'yamen-boqian', targetId: 'boqian', kind: 'agent', speaker: t('裴伯謙', 'Pei Boqian'), unlocksAgentId: 'boqian', text: t('祖宅是承祧正統，值 45 分；御賜金匾是長房體面，值 35 分。若都落到二弟手裡，外人豈不以為我被逐出宗族？', 'The residence is lineage itself, worth 45. The imperial plaque is the eldest house’s standing, worth 35. If both go to my brother, the world will think I was cast out.') },
      { id: 'yamen-zhongwen', targetId: 'zhongwen', kind: 'agent', speaker: t('裴仲文', 'Pei Zhongwen'), unlocksAgentId: 'zhongwen', text: t('金匾值 40 分，退思別院值 20 分。明年春闈在即，若既無聲望又無讀書之地，我這功名還剩下什麼？', 'The plaque is worth 40, the retreat 20. With the spring examination near, what is my title worth without standing or a place to study?') },
      { id: 'yamen-shoucheng', targetId: 'shoucheng', kind: 'agent', speaker: t('薛守成', 'Xue Shoucheng'), unlocksAgentId: 'shoucheng', text: t('水力染坊是我二十年心血，值 70 分；商鋪專賣染坊布匹，值 20 分。我只求這兩樣，祖宅金匾一分不要。', 'The mill is twenty years of my life, worth 70. Its storefront is worth 20. I ask for those two and not one point of house or plaque.') },
      { id: 'yamen-mill', targetId: 'watermill', kind: 'item', speaker: t('趙知縣', 'Magistrate Zhao'), text: t('木輪帶動齒輪，細小水聲在大堂裡格外清楚。這不是擺設，而是一個人真正會經營的產業。', 'The model wheel catches its gears. This is not ornament; it is an industry one claimant alone knows how to run.') },
      { id: 'yamen-plaque', targetId: 'imperial-plaque', kind: 'item', speaker: t('旁白', 'Narrator'), text: t('金匾未動，兩兄弟的目光卻一直沒有離開它。', 'The plaque has not moved. Neither brother has looked away from it.') },
    ],
    requiredClueIds: ['yamen-boqian', 'yamen-zhongwen', 'yamen-shoucheng'],
    masterAllocation: [0, 1, 0, 1, 2],
  },
  {
    id: 'palace',
    act: 3,
    era: t('明萬曆四年 · 乾清宮', 'Wanli 4, Ming · Palace of Heavenly Purity'),
    title: t('九邊軍國大計案', 'The Nine Borders Council'),
    concept: 'NSW',
    poster: '/game/posters/palace.webp',
    opening: t(
      '深秋夜雨敲著宮瓦。九邊地圖在長桌上鋪開，五枚權力印信壓住紙角。十四歲的天子按著御案，只說了一句：「可以不讓任何人稱心，但不能把任何一方逼進死路。」',
      'Autumn rain strikes the palace tiles. Five seals hold down the map of the Nine Borders. The young emperor rests a hand on the table. “Not everyone must be pleased. No one may be driven to ruin.”',
    ),
    storyBeats: [
      {
        speaker: t('旁白', 'Narrator'),
        text: t('深秋夜雨敲著宮瓦。九邊地圖在長桌上鋪開，五枚權力印信壓住紙角，殿門在你身後緩緩合攏。', 'Autumn rain strikes the palace tiles. Five seals pin the Nine Borders map to the long table as the hall doors close behind you.'),
        action: t('兩側宮燈明滅，地圖上的邊鎮像一條繃緊的弦。', 'Palace flames waver; the frontier line on the map resembles a drawn bowstring.'),
        focusTargetId: 'map',
        tone: 'narrator',
      },
      {
        speaker: t('萬曆帝', 'Wanli Emperor'),
        text: t('張先生、戚總兵、馮大伴，是支撐大明的三隻鼎足。可以不讓任何人稱心，但不能把任何一方逼進死路。', 'Zhang, General Qi, and Feng are the three legs of the state. Not everyone must be pleased, but no one may be driven to ruin.'),
        action: t('十四歲的天子按住御案，目光從三名重臣身上一一掠過。', 'The fourteen-year-old emperor presses a hand to the table and studies each minister.'),
        focusTargetId: 'emperor',
        tone: 'character',
      },
      {
        speaker: t('張居正', 'Zhang Juzheng'),
        text: t('沒有鹽稅與糧餉，改革只是一紙空文。財權若盡入邊軍，唐末藩鎮之禍恐將重演。', 'Without salt revenue and grain logistics, reform is ink on paper. Give all finance to the frontier and late-Tang warlord rule may return.'),
        action: t('張居正把奏疏壓在鹽引旁，緋袍映著燭火。', 'Zhang Juzheng sets his memorial beside the salt seal, crimson robes catching the firelight.'),
        focusTargetId: 'juzheng',
        tone: 'character',
      },
      {
        speaker: t('戚繼光', 'Qi Jiguang'),
        text: t('前線沒有兵符與火器，不等敵軍殺來，欠餉的士卒便會先譁變。臣要的是能守住城牆的實物。', 'Without command and firearms, unpaid soldiers may mutiny before the enemy arrives. I ask for what can hold the walls.'),
        action: t('戚繼光的鐵甲輕響，手指停在九邊兵符上方。', 'Qi Jiguang’s armor whispers as his hand hovers over the frontier tally.'),
        focusTargetId: 'jiguang',
        tone: 'character',
      },
      {
        speaker: t('馮保', 'Feng Bao'),
        text: t('皇爺總得有自己的耳目與內帑。若一點籌碼都不留，這深宮裡還有誰真正聽天子的？', 'His Majesty needs eyes and a treasury of his own. Leave the inner court no leverage, and who in this palace still obeys the throne?'),
        action: t('馮保抱緊密旨玉匣，宮燈的火苗隨他的影子縮成一線。', 'Feng Bao closes his arms around the jade decree box; the nearby flame narrows with his shadow.'),
        focusTargetId: 'fengbao',
        tone: 'character',
      },
      {
        speaker: t('系統 · 軍國任務', 'System · Council task'),
        text: t('先查明三方對五枚印信的估值。進入分配後，你還能調動一百萬兩現銀；若任何一方效用歸零，三方乘積將立即崩毀。', 'First record how all three factions value the five seals. During allocation you may also divide one million taels; if any faction reaches zero utility, the product collapses.'),
        action: t('逐一詢問三名重臣。系統會在口供齊全後開啟軍國分配桌。', 'Question all three ministers. The council allocation table will open when their testimony is complete.'),
        tone: 'system',
      },
    ],
    allocationPrompt: t('分配五枚印信，再用一百萬兩白銀調和三方效用。任何一方歸零，乘積便會崩毀。', 'Allocate five seals, then temper the result with one million taels. If one faction reaches zero, the product collapses.'),
    agents: [
      { id: 'juzheng', name: t('張居正', 'Zhang Juzheng'), role: t('內閣首輔 · 文官', 'Grand Secretary · Civil court'), color: '#7d4337' },
      { id: 'jiguang', name: t('戚繼光', 'Qi Jiguang'), role: t('薊遼總兵 · 邊軍', 'Frontier commander · Army'), color: '#53656d' },
      { id: 'fengbao', name: t('馮保', 'Feng Bao'), role: t('司禮監掌印 · 內廷', 'Chief eunuch · Inner court'), color: '#8c5b2b' },
    ],
    items: [
      { id: 'tally', name: t('九邊兵符', 'Nine Borders tally'), shortName: t('兵符', 'Tally'), description: t('調動三鎮十萬兵馬的虎符。', 'Command of three frontier garrisons.') },
      { id: 'salt', name: t('兩淮鹽引', 'Lianghuai salt monopoly'), shortName: t('鹽引', 'Salt monopoly'), description: t('每年帶來數百萬兩收入的專賣權。', 'A monopoly yielding millions of taels.') },
      { id: 'grain', name: t('糧餉督辦權', 'Grain logistics seal'), shortName: t('糧餉', 'Grain seal'), description: t('掌握九邊漕運與軍餉調度。', 'Control of frontier grain and military pay.') },
      { id: 'firearms', name: t('火器營督造', 'Firearms arsenal seal'), shortName: t('火器', 'Arsenal'), description: t('掌控神機火器研造與監工。', 'Control of imperial firearms production.') },
      { id: 'trade', name: t('茶馬互市金印', 'Tea-horse trade seal'), shortName: t('互市', 'Trade seal'), description: t('西北茶馬互市的通關御印。', 'Authority over northwestern border trade.') },
    ],
    values: [[0, 40, 30, 10, 20], [45, 5, 20, 30, 0], [20, 30, 0, 35, 15]],
    clues: [
      { id: 'palace-emperor', targetId: 'emperor', kind: 'npc', speaker: t('萬曆帝', 'Wanli Emperor'), text: t('張先生、戚總兵、馮大伴，是支撐大明的三隻鼎足。少了哪一隻，這座鼎都會倒。', 'Zhang, General Qi, and Feng are the three legs of the state. Remove one and the vessel falls.') },
      { id: 'palace-juzheng', targetId: 'juzheng', kind: 'agent', speaker: t('張居正', 'Zhang Juzheng'), unlocksAgentId: 'juzheng', text: t('鹽引值 40，糧餉值 30。沒有財賦，考成法與一條鞭法都只是紙上文章。財權若盡入邊軍，唐末藩鎮之禍未必不會重演。', 'Salt is worth 40, logistics 30. Without revenue, reform is ink on paper. Give all finance to the frontier and the warlord disasters of late Tang may return.') },
      { id: 'palace-jiguang', targetId: 'jiguang', kind: 'agent', speaker: t('戚繼光', 'Qi Jiguang'), unlocksAgentId: 'jiguang', text: t('兵符值 45，火器值 30。前線沒有統一號令與戰車火銃，不等敵軍殺來，欠餉的士卒就會先譁變。', 'The tally is worth 45, firearms 30. Without command and guns, unpaid soldiers may mutiny before the enemy arrives.') },
      { id: 'palace-fengbao', targetId: 'fengbao', kind: 'agent', speaker: t('馮保', 'Feng Bao'), unlocksAgentId: 'fengbao', text: t('火器值 35，鹽引值 30。皇爺總得有自己的耳目與內帑；若一點籌碼都不留，這深宮裡還有誰真正聽天子的？', 'Firearms are worth 35, salt 30. His Majesty needs eyes and a treasury. Leave the inner court nothing, and who in this palace still serves the throne?') },
      { id: 'palace-map', targetId: 'map', kind: 'item', speaker: t('旁白', 'Narrator'), text: t('九邊防線像一條繃緊的弦。每枚印信落下，都會讓地圖上另一處暗下去。', 'The frontier is a taut bowstring. Every seal placed brightens one place and darkens another.') },
    ],
    requiredClueIds: ['palace-juzheng', 'palace-jiguang', 'palace-fengbao'],
    masterAllocation: [1, 0, 0, 2, 0],
    masterSilver: [0, 45, 55],
  },
];

export function getNarrativeScenario(id: NarrativeScenario['id']) {
  return NARRATIVE_SCENARIOS.find((scenario) => scenario.id === id) ?? null;
}
