'use client';
import { useState } from 'react';
import { copy, type Locale } from '../i18n/copy';
export function CaseEditor({locale}:{locale:Locale}){
 const t=copy[locale]; const [agents,setAgents]=useState(['A']); const [items,setItems]=useState(['x']); const [values,setValues]=useState([[0]]); const [error,setError]=useState(''); const [pending,setPending]=useState(false);
 const resize=(na:string[],it:string[])=>setValues(v=>na.map((_,i)=>it.map((_,j)=>v[i]?.[j]??0)));
 const names=[agents,items].every(xs=>xs.length>0&&xs.every(x=>x.trim().length>0&&x.trim().length<=80)&&new Set(xs.map(x=>x.trim())).size===xs.length);
 const numbers=values.length===agents.length&&values.every(row=>row.length===items.length&&row.every(x=>Number.isInteger(x)&&x>=0&&x<=1_000_000));
 const valid=names&&numbers;
 async function submit(){if(!valid||pending)return;setError('');setPending(true);try{const res=await fetch('/api/cases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({case:{agents,items,values}})});if(!res.ok)throw new Error();const data=await res.json();location.href=`/${locale}/cases/${data.id}`;}catch{setError(t.networkError);setPending(false);}}
 return <section className="workspace" aria-busy={pending}><div className="page-heading"><p className="eyebrow">01 / {t.newCase}</p><h1>{t.newCase}</h1><p>{t.immutableHint}</p></div>
 {error&&<p role="alert">{error}</p>}
 <div className="editor-groups"><div className="panel"><div className="panel-heading"><h2>{t.people}</h2><button className="button button-secondary" type="button" onClick={()=>{const a=[...agents,String.fromCharCode(65+agents.length)];setAgents(a);resize(a,items);}}>{t.addAgent}</button></div>{agents.map((a,i)=><label key={i}>{locale==='zh-TW'?`參與者 ${i+1} 名稱`:`Agent ${i+1} name`}<input value={a} maxLength={80} onChange={e=>setAgents(agents.map((x,k)=>k===i?e.target.value:x))}/></label>)}</div>
 <div className="panel"><div className="panel-heading"><h2>{t.goods}</h2><button className="button button-secondary" type="button" onClick={()=>{const it=[...items,String.fromCharCode(120+items.length)];setItems(it);resize(agents,it);}}>{t.addItem}</button></div>{items.map((it,j)=><label key={j}>{locale==='zh-TW'?`物品 ${j+1} 名稱`:`Item ${j+1} name`}<input value={it} maxLength={80} onChange={e=>setItems(items.map((x,k)=>k===j?e.target.value:x))}/></label>)}</div></div>
 <div className="panel"><div className="panel-heading"><h2>{t.valuations}</h2><p>{t.valueHint}</p></div><div className="matrix-scroll" role="region" aria-label={t.valuations} tabIndex={0}><table><caption>{t.valuations}</caption><thead><tr><th scope="col">{t.people} / {t.goods}</th>{items.map((it,j)=><th scope="col" key={j}>{it}</th>)}</tr></thead><tbody>{agents.map((a,i)=><tr key={i}><th scope="row">{a}</th>{items.map((it,j)=><td key={j}><label className="sr-only" htmlFor={`value-${i}-${j}`}>{`${a} ${locale==='zh-TW'?'對':'value for'} ${it}${locale==='zh-TW'?' 的估值':''}`}</label><input id={`value-${i}-${j}`} type="number" min="0" max="1000000" step="1" value={Number.isNaN(values[i]?.[j])?'':values[i]?.[j]??0} onChange={e=>setValues(v=>v.map((row,ri)=>ri===i?row.map((n,c)=>c===j?(e.target.value===''?NaN:Number(e.target.value)):n):row))}/></td>)}</tr>)}</tbody></table></div></div>
 <div className="publish-panel"><div><h2>{t.preview}</h2><p>{t.immutableHint}</p>{!names&&<p role="alert">{t.invalidNames}</p>}{!numbers&&<p role="alert">{t.invalidValues}</p>}<p>{agents.length} {t.people} · {items.length} {t.goods}</p></div><button className="button button-primary" type="button" disabled={!valid||pending} onClick={submit}>{pending?t.submitting:t.publishCase}</button></div>
 </section>;
}
