'use client';
import { useEffect, useState } from 'react';
import type { CaseInput, Allocation } from '../domain/model';
import type { Aggregate } from '../server/repository';
import type { JsonScore } from '../domain/score';
import { copy, type Locale } from '../i18n/copy';
import { ScoreExplanation } from './ScoreExplanation';
import { FractionalComparison } from './FractionalComparison';
type Result={score:JsonScore;aggregate:Aggregate;caseId?:string};
export function RatingGate({locale,allocationId,caseData,owners,caseId}:{locale:Locale;allocationId:string;caseData:CaseInput;owners:Allocation;caseId?:string}){
 const t=copy[locale];const [rating,setRating]=useState('');const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');const [pending,setPending]=useState(false);const [previous,setPrevious]=useState(false);
 async function loadResults(){setError('');setPending(true);try{const r=await fetch(`/api/allocations/${allocationId}/results`);if(!r.ok)throw new Error();setResult(await r.json());}catch{setError(t.networkError);}finally{setPending(false);}}
 useEffect(()=>{if(localStorage.getItem(`fair-rated:${allocationId}`)){setPrevious(true);void loadResults();}},[allocationId]);
 async function submit(){if(!rating||pending)return;setError('');setPending(true);try{const res=await fetch(`/api/allocations/${allocationId}/ratings`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({value:Number(rating)})});if(!res.ok)throw new Error();const j=await res.json();localStorage.setItem(`fair-rated:${allocationId}`,'1');setResult(j);}catch{setError(t.networkError);}finally{setPending(false);}}
 const groups=caseData.agents.map((name,i)=>({name,items:caseData.items.filter((_,j)=>owners[j]===i)}));const targetCaseId=caseId??result?.caseId;
 return <section className="judgment"><div className="page-heading"><p className="eyebrow">{t.judgeEyebrow}</p><h1>{result?t.resultsTitle:t.judgeTitle}</h1><p>{result?(previous?t.previousResults:t.showResults):t.judgeHint}</p></div><div className="judgment-layout"><div><section className="panel bundle-panel"><div className="panel-heading"><h2>{t.allocation}</h2><span className="badge">{caseData.items.length} {t.goods}</span></div><div className="bundle-grid">{groups.map(({name,items},i)=><div className="bundle" key={i}><p className="bundle-person"><span className="person-icon" aria-hidden="true">{i+1}</span>{name}</p><ul>{items.length?items.map((item,j)=><li key={j}>{item}</li>):<li>—</li>}</ul></div>)}</div></section>{result&&<section className="panel results-panel"><h2>{t.resultsTitle}</h2><ScoreExplanation locale={locale} score={result.score} caseData={caseData}/></section>}</div><div className="judgment-side">{!result?<section className="panel vote-panel" aria-busy={pending}><p className="eyebrow">01 / 02</p><h2>{t.fairnessLabel}</h2><p>{t.ratingScale}</p>{error&&<p role="alert">{error}</p>}{!previous?<><label htmlFor="fair-rating">{t.chooseRating}</label><select id="fair-rating" aria-label={t.fairnessLabel} value={rating} disabled={pending} onChange={e=>setRating(e.target.value)}><option value="">—</option>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} — {v===1?t.veryUnfair:v===5?t.veryFair:''}</option>)}</select><div className="rating-ends"><span>{t.veryUnfair}</span><span>{t.veryFair}</span></div><button className="button button-primary" type="button" disabled={!rating||pending} onClick={submit}>{pending?t.submitting:t.submitRating}</button></>:<button className="button button-secondary" type="button" disabled={pending} onClick={loadResults}>{pending?t.submitting:t.retry}</button>}</section>:<><section className="panel vote-panel"><p className="eyebrow">02 / 02</p><h2>{t.votes}</h2><p className="aggregate-number">{result.aggregate.count}</p><p>{t.average}: {result.aggregate.mean===null?'—':result.aggregate.mean.toFixed(1)} / 5</p><ol className="histogram">{result.aggregate.histogram.map((n,i)=><li key={i}><span>{i+1}</span><span className="bar-track" aria-hidden="true"><span style={{width:`${result.aggregate.count?n/result.aggregate.count*100:0}%`}}/></span><strong>{n}</strong></li>)}</ol><p className="muted">{t.surveyCaveat}</p></section>{targetCaseId&&<><a className="button button-secondary back-to-case" href={`/${locale}/cases/${targetCaseId}`}>{t.leaderboard} ↗</a><FractionalComparison locale={locale} caseId={targetCaseId}/></>}</>}</div></div></section>;
}
